### ISSUE TITLE
Display warning if remote templates are out of date or out of sync

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/legacy-cli#112]
Display warning if remote templates are out of date or out of sync

┆Issue is synchronized with this [Jira Story](https://team-1603662928229.atlassian.net/browse/CST-26) by [Unito](https://www.unito.io)

**Comment by jyecusch** [comment]
Relates to: https://github.com/nitrictech/cli/issues/137

**Comment by tjholm** [comment]
I think we can make this a non-issue by cleanly separating our runtimes from our templates. See: https://github.com/nitrictech/buildpacks/pull/1
