### ISSUE TITLE
log file names are not platform agnostic due to certain characters

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/legacy-cli#128]
When trying to upload an artifact from .nitric logs files on a github action runner it failed due to invalid characters:
See: https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#non-supported-characters

The file name in question was:  Artifact path is not valid: /nitric-website/.nitric/logs/deploy:do-1627971365150.log. Contains character: ":". Invalid characters include: ",:,<,>,|,*,?.

**Comment by raksiv** [comment]
Had a search around for log file naming conventions.
Common usage is to stick with hyphens as the separation across the entire name
