### ISSUE TITLE
Azure - Cosmos MongoDB Database Deployment

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/legacy-cli#149]
Ability to deploy document collections to Azure Cosmo DB

* Create Collections
* Add permissions to allow services to CRUD and Query records

Relates to: https://github.com/nitrictech/membrane/issues/130

┆Issue is synchronized with this [Jira Story](https://team-1603662928229.atlassian.net/browse/CST-10) by [Unito](https://www.unito.io)

**Comment by davemooreuws** [comment]
This shouldn't be required as the collections are dynamic via mongo. We will need a deployment for the database resources though.
